------------------------------------------------------------
-- EXEMPLO DE COMO USAR:
-- EXAMPLE OF HOW TO USE:

DECLARE @T TABLE(CHAVE INT IDENTITY, CODIGO INT)

INSERT INTO @T(CODIGO)VALUES ('10')
INSERT INTO @T(CODIGO)VALUES ('20')
INSERT INTO @T(CODIGO)VALUES ('30')
INSERT INTO @T(CODIGO)VALUES ('40')
INSERT INTO @T(CODIGO)VALUES ('50')
INSERT INTO @T(CODIGO)VALUES ('60')

