CREATE FUNCTION dbo.SPLIT(@VALOR VARCHAR(8000), @CARACTER CHAR(1)) 
RETURNS @T TABLE (CHAVE INT IDENTITY, CODIGO VARCHAR(8000))

AS

BEGIN

DECLARE @POSICAO INT

WHILE (SELECT LEN(@VALOR)) > 0
BEGIN

SET @POSICAO=CHARINDEX(@CARACTER, @VALOR, 0)

INSERT INTO @T(CODIGO)
SELECT SUBSTRING(@VALOR,0,@POSICAO) CODIGO

IF @POSICAO > 0
SET @VALOR = SUBSTRING(@VALOR, @POSICAO + 1, (SELECT LEN(@VALOR)))
ELSE
SET @VALOR = NULL

END

RETURN

END