----------------- VERIFICAÇÃO DO PARAMETRO COM OS CÓDIGOS DA MINHA TABELA
----------------- VERIFICATION OF THE PARAMETER WITH THE CODES OF MY TABLE

SELECT 
    CASE 
        WHEN CODIGO in(Select CODIGO FROM DBO.SPLIT('20|10|25|30|', '|')) 
        THEN 'OK' ELSE 'Não OK'
    END Teste
FROM @T